#!/usr/bin/env bash
# hmte-init.sh - 初始化HTE项目

set -euo pipefail

TARGET="${1:-.}"
SKILL_DIR="${HMTE_SKILL_DIR:-$HOME/.hermes/profiles/default/skills/hmte}"

# 颜色输出
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${BLUE}ℹ${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }

cd "$TARGET"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Initializing HTE in: $TARGET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. 创建目录结构
info "Creating .phase_control directories..."
mkdir -p .phase_control/{evidence,verdicts,logs,pids,traces}
mkdir -p .phase_control/delegations
success "Created .phase_control directories"

# 2. 创建初始 state.json
if [ ! -f .phase_control/state.json ]; then
    info "Creating initial state.json..."
    cat > .phase_control/state.json <<EOF
{
  "session_id": "",
  "project_root": "$(pwd)",
  "mode": "skill-only",
  "goal": "",
  "current_phase": "",
  "phase_status": "pending",
  "retries_used": 0,
  "max_retries": 2,
  "started_at": "",
  "updated_at": "",
  "active_worker": "",
  "active_verifier": "",
  "evidence_paths": [],
  "verdict_path": "",
  "next_action": ""
}
EOF
    success "Created initial state.json"
else
    warn "state.json already exists, skipping"
fi

# 3. 创建 .gitkeep 文件
info "Creating .gitkeep files..."
touch .phase_control/{evidence,verdicts,logs,pids,traces}/.gitkeep
success "Created .gitkeep files"

# 4. 更新或创建 .gitignore
info "Updating .gitignore..."
if [ ! -f .gitignore ]; then
    touch .gitignore
fi

# 检查是否已有HTE规则
if ! grep -q "# HTE Runtime Files" .gitignore 2>/dev/null; then
    cat >> .gitignore <<'EOF'

# HTE Runtime Files
.phase_control/state.json
.phase_control/run.lock
.phase_control/current_phase
.phase_control/state.lock
.phase_control/state.json.tmp
.phase_control/state.json.corrupted*
.phase_control/evidence/*.json
.phase_control/verdicts/*.txt
.phase_control/logs/*.jsonl
.phase_control/pids/*.pid
.phase_control/traces/*

# Keep directory structure
!.phase_control/evidence/.gitkeep
!.phase_control/verdicts/.gitkeep
!.phase_control/logs/.gitkeep
!.phase_control/pids/.gitkeep
!.phase_control/traces/.gitkeep
EOF
    success "Updated .gitignore"
else
    warn ".gitignore already has HTE rules, skipping"
fi

# 5. 创建 README（如果不存在）
if [ ! -f .phase_control/README.md ]; then
    info "Creating .phase_control/README.md..."
    cat > .phase_control/README.md <<'EOF'
# HTE Phase Control Directory

This directory contains HTE runtime state and artifacts.

## Directory Structure

```
.phase_control/
├── state.json          # Current workflow state
├── phases.json         # Phase plan (generated by master-planner)
├── evidence/           # Evidence bundles from workers
├── verdicts/           # Verification results
├── logs/               # Command execution logs
├── pids/               # Process IDs for background tasks
└── traces/             # Execution traces
```

## Files

- **state.json**: Current state machine state (do not edit manually)
- **phases.json**: Phase plan with objectives and acceptance criteria
- **evidence/*.json**: Evidence bundles submitted by workers
- **verdicts/*.txt**: Verification results from verifier
- **logs/*.jsonl**: Command execution logs (JSONL format)

## Usage

Do not manually edit files in this directory unless you know what you're doing.
Use `hmte` commands to interact with the workflow.

## Troubleshooting

If state.json is corrupted:
```bash
# Backup corrupted file
mv .phase_control/state.json .phase_control/state.json.corrupted

# Reinitialize
hmte init
```

If lock files are stale:
```bash
rm -f .phase_control/*.lock
```
EOF
    success "Created .phase_control/README.md"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ HTE initialized successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo "  1. hmte doctor          # Check dependencies"
echo "  2. hmte start           # Start a session"
echo "  3. In Hermes: 'Use hmte skill to implement user login'"
echo ""
echo "For help: hmte help"
echo ""
